[package]
name = "chirps"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.0"
chat_birds = { path = "../chat_birds" }
crossterm = "0.29.0"
color-eyre = "0.6.5"
clap = { version = "4.5", features = ["derive"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
